// import the certificates
// corner case importing .pem files not generated by acm
// not ge
resource "aws_acm_certificate" "cert" {
  certificate_body  = var.certificate_body
  certificate_chain = var.certificate_chain
  private_key       = var.private_key

  tags = {
    Name = var.cert_tags["name"]
  }
}

// application load balancer
resource "aws_lb" "app_lb" {
  name            = var.alb_name_prefix
  subnets         = var.tf_subnet
  security_groups = [var.sg_id]
  internal        = false
  tags = {
    Name = var.alb_tags["name"]
  }
}

# Frontend
resource "aws_lb_listener" "tf_frontend" {
  load_balancer_arn = aws_lb.app_lb.arn
  port              = local.keys[count.index]
  protocol          = local.values[count.index]
  ssl_policy        = var.ssl_policy
  certificate_arn   = aws_acm_certificate.cert.arn
  count             = local.num

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.tf_target_frontend[count.index].arn
  }
}

resource "aws_lb_target_group" "tf_target_frontend" {
  name        = "${local.keys[count.index]}-on-${local.values[count.index]}"
  port        = local.keys[count.index]
  protocol    = local.values[count.index]
  target_type = "instance"
  vpc_id      = var.vpc_id
  count       = local.num
}

resource "aws_lb_target_group_attachment" "tf_attach_frontend" {
  count            = local.num
  target_group_arn = aws_lb_target_group.tf_target_frontend[count.index].arn
  target_id        = var.target_id
  port             = local.keys[count.index]
}